steps:
- name: gcr.io/moonrhythm-containers/golang:1.16.3-alpine3.13
  args:
  - go
  - build
  - -o
  - parapet-ingress-controller
  - -ldflags
  - -w -s -X main.version=$COMMIT_SHA
  - -tags=cbrotli
  - ./cmd/parapet-ingress-controller
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=1
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA, '.']

images:
- gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA
