steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --build-arg
  - VERSION=$COMMIT_SHA
  - -t
  - gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA
  - '.'

images:
- gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA
