steps:
- name: gcr.io/moonrhythm-containers/golang:1.13.6-alpine3.11
  args:
  - go
  - build
  - -o
  - parapet-ingress-controller
  - -ldflags
  - -w -s -X main.version=$TAG_NAME
  - -tags=cbrotli
  - ./cmd/parapet-ingress-controller
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=1
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/parapet-ingress-controller, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/parapet-ingress-controller, gcr.io/$PROJECT_ID/parapet-ingress-controller:$TAG_NAME]

images:
- gcr.io/$PROJECT_ID/parapet-ingress-controller
- gcr.io/$PROJECT_ID/parapet-ingress-controller:$TAG_NAME
