steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --build-arg
  - VERSION=$COMMIT_SHA
  - --build-arg
  - GOAMD64=v3
  - -t
  - gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA
  - '.'
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --build-arg
  - VERSION=$COMMIT_SHA
  - --build-arg
  - GOAMD64=v1
  - -t
  - gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA-amd64v1
  - '.'
  waitFor: ['-']
images:
- gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA
- gcr.io/$PROJECT_ID/parapet-ingress-controller:$COMMIT_SHA-amd64v1
