apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: parapet-ingress-controller
  name: parapet-ingress-controller
  namespace: parapet-ingress-controller
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: parapet-ingress-controller
  template:
    metadata:
      annotations:
        prometheus.io/port: "9187"
        prometheus.io/scrape: "true"
      labels:
        app: parapet-ingress-controller
    spec:
      containers:
      - name: parapet-ingress-controller
        image: registry.moonrhythm.io/parapet-ingress-controller:v0.13.12
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: TRUST_PROXY
          value: cloudflare
        - name: DISABLE_LOG
          value: "true"
        - name: HOST_CONCURRENT_CAPACITY
          value: "10000"
        - name: HOST_COUNTRY_HEADER
          value: Cf-Ipcountry
        - name: HOST_COUNTRY_CONCURRENT_CAPACITY
          value: "4000"
        - name: PROFILER
          value: "false"
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
      serviceAccount: parapet-ingress-controller
      serviceAccountName: parapet-ingress-controller
      terminationGracePeriodSeconds: 300
  updateStrategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
