apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: parapet-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: parapet-ingress-controller
subjects:
- kind: ServiceAccount
  name: parapet-ingress-controller
