apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: parapet-ingress-controller
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - get
