apiVersion: v1
kind: Service
metadata:
  labels:
    app: parapet-ingress-controller
  name: parapet-ingress-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: parapet-ingress-controller
