name: Go Build
on:
  push:
    branches:
    - master
    paths:
    - 'go/**'
    - '.github/workflows/go-build.yaml'
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    name: Build
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      id: auth
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        token_format: access_token
    - uses: docker/login-action@v3
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/login-action@v3
      with:
        registry: asia-southeast3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/setup-buildx-action@v3
      with:
        version: latest
        platforms: linux/amd64
    - uses: docker/build-push-action@v6
      with:
        provenance: false
        context: go
        build-args: |
          VERSION=${{ github.sha }}
          GOAMD64=v3
        push: true
        tags: |
          us-docker.pkg.dev/moonrhythm-containers/gcr.io/parapet-ingress-controller:${{ github.sha }}
          asia-southeast3-docker.pkg.dev/moonrhythm-core/public/parapet-ingress-controller:${{ github.sha }}
    - uses: docker/build-push-action@v6
      with:
        provenance: false
        context: go
        build-args: |
          VERSION=${{ github.sha }}
          GOAMD64=v1
        push: true
        tags: |
          us-docker.pkg.dev/moonrhythm-containers/gcr.io/parapet-ingress-controller:${{ github.sha }}-amd64v1
          asia-southeast3-docker.pkg.dev/moonrhythm-core/public/parapet-ingress-controller:${{ github.sha }}-amd64v1
