name: Go Test
on:
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-test.yaml'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-test.yaml'
jobs:
  runner-job:
    runs-on: self-hosted
    strategy:
      matrix:
        go: ['1.26.5']
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: go get -t -v ./...
    - run: go vet ./...
    - run: go test -race ./...
